### ISSUE TITLE
BDD

### ISSUE THREAD

**Issue by AyatoKirishima** [WhatANiceDayToCode/Blog-Project#10]
![image](https://user-images.githubusercontent.com/42692272/148581503-c452069d-2652-45c1-89be-8e6f2248f2c8.png)

**Comment by Spl4shh** [comment]
alors je viens de corriger normalement ca devrait etre bon, mais tu dois selectionner une base avant d'importer ton fichier

**Comment by Spl4shh** [comment]
@AyatoKirishima Tu testeras et tu me diras
